version: '3'

services:
  mysql_dev:
    image: mysql:5.7
    container_name: fastapi_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DEV_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DEV_DATABASE}
    ports:
      - "${MYSQL_DEV_PORT}:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: fastapi_adminer
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  mysql_dev_data:
