"""empty message

Revision ID: 8268a93ec712
Revises: e228fa2d7faa
Create Date: 2023-09-27 15:02:00.371151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8268a93ec712"
down_revision = "e228fa2d7faa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_item_category_id_category", "item", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_item_category_id_category"),
        "item",
        "category",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_item_category_id_category"), "item", type_="foreignkey")
    op.create_foreign_key(
        "fk_item_category_id_category", "item", "category", ["category_id"], ["id"]
    )
    # ### end Alembic commands ###
