"""empty message

Revision ID: 613cef3e85a6
Revises: df8e6b5e1bc9
Create Date: 2023-09-21 11:53:22.138518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "613cef3e85a6"
down_revision = "df8e6b5e1bc9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=64), nullable=False),
        sa.Column("hashed_password", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
    )
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["user.id"], name=op.f("fk_category_creator_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
    )
    op.add_column("item", sa.Column("name", sa.String(length=255), nullable=False))
    op.add_column(
        "item", sa.Column("description", sa.String(length=5000), nullable=False)
    )
    op.add_column("item", sa.Column("category_id", sa.Integer(), nullable=False))
    op.add_column("item", sa.Column("creator_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_item_category_id_category"),
        "item",
        "category",
        ["category_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_item_creator_id_user"), "item", "user", ["creator_id"], ["id"]
    )
    op.drop_column("item", "data")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item", sa.Column("data", mysql.JSON(), nullable=True))
    op.drop_constraint(op.f("fk_item_creator_id_user"), "item", type_="foreignkey")
    op.drop_constraint(op.f("fk_item_category_id_category"), "item", type_="foreignkey")
    op.drop_column("item", "creator_id")
    op.drop_column("item", "category_id")
    op.drop_column("item", "description")
    op.drop_column("item", "name")
    op.drop_table("category")
    op.drop_table("user")
    # ### end Alembic commands ###
