"""empty message

Revision ID: e228fa2d7faa
Revises: 7b5cb839a50a
Create Date: 2023-09-26 16:02:00.417497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e228fa2d7faa"
down_revision = "7b5cb839a50a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_item_name"), "item", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_item_name"), "item", type_="unique")
    # ### end Alembic commands ###
