"""empty message

Revision ID: 7b5cb839a50a
Revises: 613cef3e85a6
Create Date: 2023-09-22 16:15:31.118758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b5cb839a50a"
down_revision = "613cef3e85a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_category_name"), "category", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_category_name"), "category", type_="unique")
    # ### end Alembic commands ###
