"""empty message

Revision ID: 42e8d8399cfa
Revises: 8268a93ec712
Create Date: 2023-10-02 10:43:33.266619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "42e8d8399cfa"
down_revision = "8268a93ec712"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("category", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("category", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("item", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("item", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("item", "updated_at")
    op.drop_column("item", "created_at")
    op.drop_column("category", "updated_at")
    op.drop_column("category", "created_at")
    # ### end Alembic commands ###
