"""empty message

Revision ID: ead0e63885ca
Revises: b13c466d06ea
Create Date: 2024-01-25 15:49:46.450347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ead0e63885ca"
down_revision = "b13c466d06ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category",
        "description",
        existing_type=mysql.VARCHAR(length=5000),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category",
        "description",
        existing_type=mysql.VARCHAR(length=5000),
        nullable=True,
    )
    # ### end Alembic commands ###
