"""empty message

Revision ID: b13c466d06ea
Revises: 42e8d8399cfa
Create Date: 2024-01-25 15:49:14.531770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b13c466d06ea"
down_revision = "42e8d8399cfa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "category", sa.Column("description", sa.String(length=5000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category", "description")
    # ### end Alembic commands ###
